#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    
    total = sum(arr)                 # Python ints handle 64-bit fine
    mn = total - max(arr)            # sum of the smallest four
    mx = total - min(arr)            # sum of the largest four
    print(mn, mx)


if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
