#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    period = s[-2:]         # "AM" or "PM"
    hh = int(s[:2])         # hour as number, e.g., 7
    mmss = s[2:8]           # the ":mm:ss" part, e.g., ":05:45"

    if period == "AM":
        if hh == 12:        # 12AM is 00
            hh = 0
        # else keep hh as is
    else:  # "PM"
        if hh != 12:        # add 12 except for 12PM
            hh += 12

    return f"{hh:02d}{mmss}"
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
